⬆️ (react-native) calling getNode on the ref is no longer necessary
react-native-community/react-native-safe-area-view pull request #110
Opened 2020-03-31 17:00 UTC by ArrayZoneYour

# Summary

1. Calling `getNode()` on the ref of an Animated component is no longer necessary after react-native 0.62.
 [Github Link](https://github.com/facebook/react-native/blob/0b9ea60b4fee8cacc36e7160e31b91fc114dbc0d/Libraries/Animated/src/createAnimatedComponent.js#L149)
 [StackOverflow Link](https://stackoverflow.com/questions/60946364/react-native-showing-warning-calling-getnode-on-the-ref-of-an-animated-comp
)

2. improve AnimatedView's type

## Test Plan

`yarn prepare` worked

console warning disappear

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2020-03-31 18:11 UTC, ajiehatajie commented
same issue rn 0.62

2020-04-02 07:43 UTC, orzhtml commented
什么时候能合并代码

2020-04-02 09:36 UTC, VDetish commented
Да, мы тоже ждём.

2020-04-06 08:22 UTC, kulazhenkoa-digicode commented
rn0.62 - waiting for fix

2020-04-13 03:40 UTC, beeman commented
Pinging @brentvatne, could you please consider looking into merging this one-liner Thanks in advance!

2020-04-17 00:18 UTC, brentvatne commented
this should be made backwards compatible, so it will work in both 0.62 apps and older apps

2020-04-17 00:19 UTC, brentvatne requested changes
should be backwards compatible

2020-04-18 23:57 UTC, brentvatne approved these changes

2020-04-18 23:57 UTC, merged

2020-04-19 01:27 UTC, brentvatne commented
this is released in react-native-safe-area-view@1.1.0! thanks!