Added support for new iPad Pro safe area insets
react-native-community/react-native-safe-area-view pull request #55
Opened 2019-01-06 16:57 UTC by cesargdm

Added support for new iPad Pro models, 11-inch and 12.9 inch (3rd generation).
Please checkup the new variables names.

See https://github.com/react-native-community/react-native-safe-area-view/issues/54

2019-01-07 00:22 UTC, brentvatne commented
thanks! it's very unfortunate that we need to do this but until the layout context api lands upstream in react-native it'll work

2019-01-07 00:24 UTC, brentvatne requested changes
just one small change and it's good to go

2019-01-07 00:24 UTC, brentvatne commented on index.js
> +  if (Platform.OS === 'web') return false;
`if (Platform.OS !== 'ios')`

2019-01-08 00:43 UTC, cesargdm commented on index.js
> +  if (Platform.OS === 'web') return false;
Fixed :)

2019-01-08 22:18 UTC, cesargdm commented
Fixed! :)

2019-01-09 19:22 UTC, merged

2020-04-12 23:57 UTC, bradleyflood commented on index.js
> +          return 20;
Why `20` for iPadPro and not `34` to be the same as the iPhoneX? They both have the "Home Line" and need the same amount of clearance right? @cesargdm

2020-04-12 23:59 UTC, bradleyflood commented on index.js
> +          return 20;
Why `20` for iPadPro and not `34` to be the same as the iPhoneX? They both have the "Home Line" and need the same amount of clearance right? @cesargdm

2020-04-13 00:01 UTC, bradleyflood commented on index.js
> +          return 20;
iPhoneX
![Screen Shot 2020-04-13 at 10 00 25](https://user-images.githubusercontent.com/1085976/79082884-a583b180-7d6d-11ea-95b4-b8665541c12c.png)

iPadPro
![Screen Shot 2020-04-13 at 10 00 31](https://user-images.githubusercontent.com/1085976/79082881-a3b9ee00-7d6d-11ea-8fa3-f269562158ca.png)

2020-04-13 18:57 UTC, brentvatne commented
@bradleyflood - i don't recommend using the old version of react-native-safe-area-view that includes this code, the latest version uses react-native-safe-area-context to correctly determine device safe areas with the platform native apis